wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: Poems
epochs:
  desc: null
  value: 30
_wandb:
  desc: null
  value:
    python_version: 3.9.2
    cli_version: 0.15.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1694254123.601511
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.2
      5: 0.15.10
      8:
      - 1
      - 3
      - 5
