wandb_version: 1

architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: Poems
embedding_dim:
  desc: null
  value: 256
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.026565108068213612
optimizer:
  desc: null
  value: adam
_wandb:
  desc: null
  value:
    python_version: 3.9.2
    cli_version: 0.15.10
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1694345449.219359
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      3:
      - 2
      - 23
      - 37
      4: 3.9.2
      5: 0.15.10
      8:
      - 1
      - 3
      - 5
